//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTCONSTRUCCIONES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alquiler
    {
        public Alquiler()
        {
            this.EntregaAlquilers = new HashSet<EntregaAlquiler>();
        }
    
        public int IdAlquiler { get; set; }
        public string Nombre { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaAlquiler { get; set; }
        public int HorasAlquiladas { get; set; }
        public decimal PagoHora { get; set; }
        public int IdProyecto { get; set; }
    
        public virtual ICollection<EntregaAlquiler> EntregaAlquilers { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
