//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTCONSTRUCCIONES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public Cargo()
        {
            this.Empleadoes = new HashSet<Empleado>();
        }
    
        public int IdCargo { get; set; }
        public decimal Salario { get; set; }
        public string CargoDesc { get; set; }
    
        public virtual ICollection<Empleado> Empleadoes { get; set; }
    }
}
