//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTCONSTRUCCIONES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public Compra()
        {
            this.DetalleCompras = new HashSet<DetalleCompra>();
        }
    
        public int IdCompra { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public decimal GastoTotal { get; set; }
        public Nullable<int> IdProyecto { get; set; }
    
        public virtual ICollection<DetalleCompra> DetalleCompras { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
