//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTCONSTRUCCIONES
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleEntrada
    {
        public int IdEntrada { get; set; }
        public int IdProd { get; set; }
        public int Cantidad { get; set; }
        public string DesEstado { get; set; }
    
        public virtual Entrada_Inventario Entrada_Inventario { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
