//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTCONSTRUCCIONES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Salida_Inventario = new HashSet<Salida_Inventario>();
            this.Proyectoes = new HashSet<Proyecto>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int IdEmpleado { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string INSS { get; set; }
        public int IdTipo { get; set; }
        public int IdCargo { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual ICollection<Salida_Inventario> Salida_Inventario { get; set; }
        public virtual ICollection<Proyecto> Proyectoes { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
        public virtual TipoEmpleado TipoEmpleado { get; set; }
    }
}
