//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTCONSTRUCCIONES
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntregaAlquiler
    {
        public int IdEntregaAlquiler { get; set; }
        public int HorasExcedidas { get; set; }
        public decimal PagoFinal { get; set; }
        public int IdAlquiler { get; set; }
    
        public virtual Alquiler Alquiler { get; set; }
    }
}
