//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTCONSTRUCCIONES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planilla
    {
        public Planilla()
        {
            this.Proyectoes = new HashSet<Proyecto>();
        }
    
        public int IdPlanilla { get; set; }
        public Nullable<decimal> Presupuesto { get; set; }
        public Nullable<decimal> MontoACobrar { get; set; }
        public Nullable<decimal> FueraDelPresupuesto { get; set; }
    
        public virtual ICollection<Proyecto> Proyectoes { get; set; }
    }
}
